# Generated by Django 5.0 on 2023-12-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=20)),
                ('salary', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
